// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v4.25.1
// source: mosquitto_auth/mosquitto_auth.proto

package mosquitto_auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BasicAuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username      string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ClientId      string `protobuf:"bytes,3,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ClientAddress string `protobuf:"bytes,4,opt,name=clientAddress,proto3" json:"clientAddress,omitempty"`
}

func (x *BasicAuthRequest) Reset() {
	*x = BasicAuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mosquitto_auth_mosquitto_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicAuthRequest) ProtoMessage() {}

func (x *BasicAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mosquitto_auth_mosquitto_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicAuthRequest.ProtoReflect.Descriptor instead.
func (*BasicAuthRequest) Descriptor() ([]byte, []int) {
	return file_mosquitto_auth_mosquitto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *BasicAuthRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BasicAuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *BasicAuthRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *BasicAuthRequest) GetClientAddress() string {
	if x != nil {
		return x.ClientAddress
	}
	return ""
}

type BasicAuthReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *BasicAuthReply) Reset() {
	*x = BasicAuthReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mosquitto_auth_mosquitto_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicAuthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicAuthReply) ProtoMessage() {}

func (x *BasicAuthReply) ProtoReflect() protoreflect.Message {
	mi := &file_mosquitto_auth_mosquitto_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicAuthReply.ProtoReflect.Descriptor instead.
func (*BasicAuthReply) Descriptor() ([]byte, []int) {
	return file_mosquitto_auth_mosquitto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *BasicAuthReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type AclCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ClientId string `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Topic    string `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Access   int32  `protobuf:"varint,4,opt,name=access,proto3" json:"access,omitempty"`
	Qos      int32  `protobuf:"varint,5,opt,name=qos,proto3" json:"qos,omitempty"`
	Retain   int32  `protobuf:"varint,6,opt,name=retain,proto3" json:"retain,omitempty"`
}

func (x *AclCheckRequest) Reset() {
	*x = AclCheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mosquitto_auth_mosquitto_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AclCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AclCheckRequest) ProtoMessage() {}

func (x *AclCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mosquitto_auth_mosquitto_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AclCheckRequest.ProtoReflect.Descriptor instead.
func (*AclCheckRequest) Descriptor() ([]byte, []int) {
	return file_mosquitto_auth_mosquitto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AclCheckRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AclCheckRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AclCheckRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AclCheckRequest) GetAccess() int32 {
	if x != nil {
		return x.Access
	}
	return 0
}

func (x *AclCheckRequest) GetQos() int32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

func (x *AclCheckRequest) GetRetain() int32 {
	if x != nil {
		return x.Retain
	}
	return 0
}

type AclCheckReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *AclCheckReply) Reset() {
	*x = AclCheckReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mosquitto_auth_mosquitto_auth_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AclCheckReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AclCheckReply) ProtoMessage() {}

func (x *AclCheckReply) ProtoReflect() protoreflect.Message {
	mi := &file_mosquitto_auth_mosquitto_auth_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AclCheckReply.ProtoReflect.Descriptor instead.
func (*AclCheckReply) Descriptor() ([]byte, []int) {
	return file_mosquitto_auth_mosquitto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *AclCheckReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_mosquitto_auth_mosquitto_auth_proto protoreflect.FileDescriptor

var file_mosquitto_auth_mosquitto_auth_proto_rawDesc = []byte{
	0x0a, 0x23, 0x6d, 0x6f, 0x73, 0x71, 0x75, 0x69, 0x74, 0x74, 0x6f, 0x5f, 0x61, 0x75, 0x74, 0x68,
	0x2f, 0x6d, 0x6f, 0x73, 0x71, 0x75, 0x69, 0x74, 0x74, 0x6f, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6d, 0x6f, 0x73, 0x71, 0x75, 0x69, 0x74, 0x74, 0x6f,
	0x5f, 0x61, 0x75, 0x74, 0x68, 0x22, 0x8c, 0x01, 0x0a, 0x10, 0x42, 0x61, 0x73, 0x69, 0x63, 0x41,
	0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x24,
	0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x22, 0x24, 0x0a, 0x0e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x41, 0x75, 0x74,
	0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0xa1, 0x01, 0x0a, 0x0f, 0x41,
	0x63, 0x6c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x71, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x71, 0x6f, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x74, 0x61, 0x69, 0x6e,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x74, 0x61, 0x69, 0x6e, 0x22, 0x23,
	0x0a, 0x0d, 0x41, 0x63, 0x6c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x32, 0xa8, 0x01, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12,
	0x4f, 0x0a, 0x09, 0x42, 0x61, 0x73, 0x69, 0x63, 0x41, 0x75, 0x74, 0x68, 0x12, 0x20, 0x2e, 0x6d,
	0x6f, 0x73, 0x71, 0x75, 0x69, 0x74, 0x74, 0x6f, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x42, 0x61,
	0x73, 0x69, 0x63, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x6d, 0x6f, 0x73, 0x71, 0x75, 0x69, 0x74, 0x74, 0x6f, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x42, 0x61, 0x73, 0x69, 0x63, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x4c, 0x0a, 0x08, 0x41, 0x63, 0x6c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x1f, 0x2e, 0x6d,
	0x6f, 0x73, 0x71, 0x75, 0x69, 0x74, 0x74, 0x6f, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x41, 0x63,
	0x6c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x6d, 0x6f, 0x73, 0x71, 0x75, 0x69, 0x74, 0x74, 0x6f, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x41,
	0x63, 0x6c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x12,
	0x5a, 0x10, 0x2e, 0x2f, 0x6d, 0x6f, 0x73, 0x71, 0x75, 0x69, 0x74, 0x74, 0x6f, 0x5f, 0x61, 0x75,
	0x74, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mosquitto_auth_mosquitto_auth_proto_rawDescOnce sync.Once
	file_mosquitto_auth_mosquitto_auth_proto_rawDescData = file_mosquitto_auth_mosquitto_auth_proto_rawDesc
)

func file_mosquitto_auth_mosquitto_auth_proto_rawDescGZIP() []byte {
	file_mosquitto_auth_mosquitto_auth_proto_rawDescOnce.Do(func() {
		file_mosquitto_auth_mosquitto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_mosquitto_auth_mosquitto_auth_proto_rawDescData)
	})
	return file_mosquitto_auth_mosquitto_auth_proto_rawDescData
}

var file_mosquitto_auth_mosquitto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mosquitto_auth_mosquitto_auth_proto_goTypes = []interface{}{
	(*BasicAuthRequest)(nil), // 0: mosquitto_auth.BasicAuthRequest
	(*BasicAuthReply)(nil),   // 1: mosquitto_auth.BasicAuthReply
	(*AclCheckRequest)(nil),  // 2: mosquitto_auth.AclCheckRequest
	(*AclCheckReply)(nil),    // 3: mosquitto_auth.AclCheckReply
}
var file_mosquitto_auth_mosquitto_auth_proto_depIdxs = []int32{
	0, // 0: mosquitto_auth.Greeter.BasicAuth:input_type -> mosquitto_auth.BasicAuthRequest
	2, // 1: mosquitto_auth.Greeter.AclCheck:input_type -> mosquitto_auth.AclCheckRequest
	1, // 2: mosquitto_auth.Greeter.BasicAuth:output_type -> mosquitto_auth.BasicAuthReply
	3, // 3: mosquitto_auth.Greeter.AclCheck:output_type -> mosquitto_auth.AclCheckReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mosquitto_auth_mosquitto_auth_proto_init() }
func file_mosquitto_auth_mosquitto_auth_proto_init() {
	if File_mosquitto_auth_mosquitto_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mosquitto_auth_mosquitto_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasicAuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mosquitto_auth_mosquitto_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasicAuthReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mosquitto_auth_mosquitto_auth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AclCheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mosquitto_auth_mosquitto_auth_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AclCheckReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mosquitto_auth_mosquitto_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mosquitto_auth_mosquitto_auth_proto_goTypes,
		DependencyIndexes: file_mosquitto_auth_mosquitto_auth_proto_depIdxs,
		MessageInfos:      file_mosquitto_auth_mosquitto_auth_proto_msgTypes,
	}.Build()
	File_mosquitto_auth_mosquitto_auth_proto = out.File
	file_mosquitto_auth_mosquitto_auth_proto_rawDesc = nil
	file_mosquitto_auth_mosquitto_auth_proto_goTypes = nil
	file_mosquitto_auth_mosquitto_auth_proto_depIdxs = nil
}
